clear
echo "copy and paste these into python interpreter"
echo "---------------"
echo "import nltk"
echo "nltk.download()"
echo "d"
echo "punkt"
echo "d"
echo "wordnet"
echo "q"
echo "quit()"
echo ""
echo ""
echo "---------------"
python
